kind: Service
apiVersion: v1
metadata:
  name: neo4j-dev
spec:
  selector:
    app: neo4j-dev
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 7474
  - protocol: TCP
    name: ws
    port: 7473
    targetPort: 7473
  - protocol: TCP
    name: ws-2
    port: 7687
    targetPort: 7687
  type: LoadBalancer